### ISSUE TITLE
Improve directed sales (venta dirigida) "canje" workflow

### ISSUE THREAD

**Issue by rasca** [fuegoaustral/ticketera#18]
It's being done in an excel. Analyse the current workflow and implement in the the ticketera so it's just one step.

Take into account how cash is handled . That was the one thing that wasn't so straight forward in the current setup.

**Comment by piotromashov** [comment]
The idea is to analyse the current workflow, and what we are doing in manually in excel, because now we have incoungrencies between tickets assigned on the excel, and the ones assigned effectively to people.
