### ISSUE TITLE
Camp - CU 02 - 1 bono "no transferible" de 10 comprados

### ISSUE THREAD

**Issue by juanbautista88** [fuegoaustral/ticketera#69]
Lider de camp compro 10 bonos, los recibio a los 10 pero recibio 9 bonos "transferibles".

![image](https://github.com/user-attachments/assets/51dc8e35-9ebf-4eac-b6ce-3f461fc62c61)

Al parecer el decimo bono lo tiene asignado como propio (el ultimo de la siguiente imagen es el mismo que el user tiene asignado en la proxima), entiendo que deberia poder transferirlo tambien.
![image](https://github.com/user-attachments/assets/0b9b76f0-08a8-4ad8-88ea-04d12c54eb24)
![image](https://github.com/user-attachments/assets/7380aaec-67d4-4821-879a-afd32d337fb3)

**Comment by rasca** [comment]
El "mi bono" hay un botón arriba de todo que dice "Transferir mi bono" que habilitá este flow que comentás.
